# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
#    disable_csrf_role: ROLE_API
    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    routing_loader:
        default_format: json
        include_format: false
    view:
        mime_types:
            json: ['application/json']
        view_response_listener: 'force'

#    exception:
#        codes:
#            Ddd\Exception\MyException: 403
#        messages:
#            Ddd\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
